version: '3.8'
services:
  main:
    container_name: api-products
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 5 &&
      php /var/www/html/artisan migrate &&
      php -S 0.0.0.0:80 -t public"
    ports:
      - 80:80
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - dbData:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  dbData:
    driver: local
